### ISSUE TITLE
Recommended strategy to split producer code and worker code ?

### ISSUE THREAD

**Issue by nmoreaud** [brthor/Gofer.NET#54]
Hello
It is written [on this page](https://github.com/brthor/Gofer.NET/blob/master/docs/workers.md#workers-must-have-access-to-the-queued-code) that the producer and the workers must share "tasks" code.
This seems counter-intuitive to me for two reasons:
- Main Gofer examples show a producer with tasks code, and workers without (tasks are processed at client side!). By reading examples, we can think that tasks are executed by the producer (lambda evaluation).
- Worker and producer generally have different library requirements. Ex: if we work on image processing tasks, the worker needs an image processing library but the producer doesn't.

What is the recommended strategy to split producer code and worker code so that the producer remains agnostic about how the worker processes tasks?

**Comment by brthor** [comment]
Utilizing different sets of libraries in the producers and workers is unlikely to work with Gofer.NET without some clever hacking. 

Since the target function location is serialized, and not something more abstract like a string, the producer and worker both need to have access to the target function.

One idea would be to have a sort of virtual assembly in the producer where tasks are defined, but do nothing. In the worker, this assembly would need to be replaced with one of the same Full Name with the task bodies replaced with the real code.

In the general case, this use-case is currently unsupported by Gofer.NET. 

If you get it working though, please leave a comment on how you accomplished it and perhaps the docs could get updated.

**Comment by nmoreaud** [comment]
Thanks for your answer. I guess I can make it work with a global variable (singleton or something like that). However, this is the most basic use case I can think of. For the project I'm working on, I need way more flexibility. I won't be able to test further this library, as it doesn't fulfill my needs

**Comment by brthor** [comment]
I can understand that there are some use-cases where this type of separation makes sense.

AFAIK this is not generally supported by distributed task libraries that work directly within the language like this one.

A more abstract task system that works on the process/command level may be more inline with what you need.

Currently, we have no plans to support this scenario officially so I'm going to close this issue out.

If you get it working though, I'd still be interested to hear how you did it.

**Comment by brthor** [comment]
> Main Gofer examples show a producer with tasks code, and workers without (tasks are processed at client side!). By reading examples, we can think that tasks are executed by the producer (lambda evaluation).

Can you point out where you are seeing this?

In the guided example, the worker has a project reference to the producer so the producer's assembly is included as a dependency.

https://brthor.github.io/Gofer.NET/example#add-langversion-property

```msbuild
<ItemGroup>
  <ProjectReference Include="..\primary\primary.csproj" />
</ItemGroup>
```
